name = "semantic-uncertainty-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Account ID (get from Cloudflare dashboard)
account_id = "bbafb0eab53c624e2e9f1f21e1d7a273"

# Environment variables - NEVER put actual secrets in this file!
# Use: wrangler secret put API_KEY_SECRET for production deployment
[env.production.vars]
API_KEY_SECRET = "john-yue-demo-key-secure-2025"
RATE_LIMIT_PER_MINUTE = "100"
ALLOWED_ORIGINS = "https://semanticuncertainty.com"

[env.staging.vars]
# API_KEY_SECRET is set via: wrangler secret put API_KEY_SECRET
RATE_LIMIT_PER_MINUTE = "50"
ALLOWED_ORIGINS = "https://staging.semanticuncertainty.com"

# KV namespace for rate limiting and usage tracking (commented out for now)
# [[kv_namespaces]]
# binding = "USAGE_TRACKER"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Durable Objects for real-time rate limiting (commented out for now)
# [[durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiter"

# WebAssembly bindings for Rust code (commented out for now)
# [[wasm_modules]]
# name = "SEMANTIC_ENGINE"
# source = "core-engine/pkg/semantic_uncertainty_engine_bg.wasm"

# Custom domains (commented out for now)
# [[routes]]
# pattern = "api.semanticuncertainty.com/*"
# zone_name = "semanticuncertainty.com"

# Pricing tier (commented out for now)
# usage_model = "bundled"  # Use "unbound" for high-volume 