# 🌐 Global Edge Optimization Configuration
# Multi-region deployment with CDN optimization for Semantic Uncertainty API

name = "semantic-uncertainty-global"
main = "src/edge-worker.js"
compatibility_date = "2024-01-01"
account_id = "bbafb0eab53c624e2e9f1f21e1d7a273"

# 🗺️ Global Environment Configuration
[env.global]
vars = { 
  GLOBAL_CDN_ENABLED = "true",
  CACHE_TTL_SECONDS = "300",
  PREFETCH_ENABLED = "true",
  REGIONAL_FAILOVER = "true",
  PERFORMANCE_TARGET_MS = "5"
}

# 🇺🇸 Americas Region
[env.americas]
vars = { 
  REGION = "americas",
  PRIMARY_ZONES = "us-east-1,us-west-1",
  SECONDARY_ZONES = "ca-central-1,sa-east-1",
  CACHE_STRATEGY = "aggressive",
  FAILOVER_THRESHOLD_MS = "50"
}

# 🇪🇺 Europe Region  
[env.europe]
vars = { 
  REGION = "europe",
  PRIMARY_ZONES = "eu-west-1,eu-central-1", 
  SECONDARY_ZONES = "eu-west-2,eu-north-1",
  CACHE_STRATEGY = "balanced",
  FAILOVER_THRESHOLD_MS = "50"
}

# 🇦🇺 Asia-Pacific Region
[env.asia]
vars = { 
  REGION = "asia",
  PRIMARY_ZONES = "ap-southeast-1,ap-northeast-1",
  SECONDARY_ZONES = "ap-southeast-2,ap-south-1", 
  CACHE_STRATEGY = "balanced",
  FAILOVER_THRESHOLD_MS = "75"
}

# 📊 KV Namespaces for Edge Caching
[[kv_namespaces]]
binding = "GLOBAL_CACHE"
id = "semantic_cache_global"
preview_id = "semantic_cache_preview"

[[kv_namespaces]]
binding = "ANALYTICS_STORE"
id = "semantic_analytics"
preview_id = "semantic_analytics_preview"

[[kv_namespaces]]
binding = "PERFORMANCE_METRICS"
id = "semantic_performance"
preview_id = "semantic_performance_preview"

# 🚀 Durable Objects for Regional State
[[durable_objects.bindings]]
name = "REGIONAL_COORDINATOR"
class_name = "RegionalCoordinator"

[[durable_objects.bindings]]
name = "PERFORMANCE_MONITOR"
class_name = "PerformanceMonitor"

# 🔄 Custom Domains for Regional Routing
[[routes]]
pattern = "api-us.semanticuncertainty.com/*"
zone_name = "semanticuncertainty.com"
custom_domain = true

[[routes]]
pattern = "api-eu.semanticuncertainty.com/*" 
zone_name = "semanticuncertainty.com"
custom_domain = true

[[routes]]
pattern = "api-asia.semanticuncertainty.com/*"
zone_name = "semanticuncertainty.com"
custom_domain = true

# ⚡ Performance Optimization
[build]
command = "npm run build:edge"
cwd = "edge-optimization"

[build.upload]
format = "service-worker"
main = "./dist/edge-worker.js"

# 🎯 Usage Limits for Performance
usage_model = "unbound"
logpush = true

[limits]
cpu_ms = 50
memory_mb = 128